apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdap-sandbox
  name: cdap
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cdap
  type: NodePort
